newproject/newproject.component.css
newproject/newproject.component.html

We should talk about the design later. It's a basic template for creating project but more features will be followed.

basic template for creating project

---

nfafrontend/src/app/newproject/newproject.component.html

change German to English. I'll stick to English then Thanks.

change terms to english

---

README.md
nfafrontend/src/app/newproject/newproject.component.ts

I changed some attributes name, to be english instead of german

renamed attribute "kundenName" into "customerName"

---

nfafrontend/src/app/home/home.component.html
nfafrontend/src/app/newnfa/newnfa.component.html
nfafrontend/src/app/newproject/newproject.component.html
nfafrontend/src/assets/i18n/de.json
nfafrontend/src/assets/i18n/en.json

- new project
- new nfa (incl. selection options)

Translations for 2 Pages complete

---

nfafrontend/src/app/app.module.ts
nfafrontend/src/app/editable-table/editable-table.component.spec.ts
nfafrontend/src/app/editable-table/editable-table.component.ts
nfafrontend/src/app/editable-table/editable-table.module.ts
nfafrontend/src/app/editable-table/editable-table.service.spec.ts
nfafrontend/src/app/editable-table/editable-table.service.ts
nfafrontend/src/app/newproject/newproject.component.css
nfafrontend/src/app/newproject/newproject.component.html
nfafrontend/src/app/newproject/newproject.component.spec.ts
nfafrontend/src/app/newproject/newproject.component.ts
nfafrontend/src/app/util/table-cell.ts
nfafrontend/src/app/util/table-row.ts

I added editable table componenet to use for editing , deleting and adding new type to the project
link the the project html and component to this new component
only UI no changed in the backend

Add editable table componenet and link it to the project componenet

---

nfabackend/src/main/java/com/msg/nfabackend/entities/Project.java
nfabackend/src/main/java/com/msg/nfabackend/entities/Type.java
nfabackend/src/main/java/com/msg/nfabackend/resources/TypeResource.java

create "Type" entity and modify the "Project" entity to include many to many

---

nfabackend/src/main/java/com/msg/nfabackend/entities/Project.java
nfabackend/src/main/java/com/msg/nfabackend/entities/Type.java
nfabackend/src/main/java/com/msg/nfabackend/services/QueryService.java
nfabackend/src/main/resources-filtered/META-INF/persistence.xml
nfabackend/src/main/resources/ddl/nfa_projekt.ddl
nfafrontend/src/app/current-project/current-project.component.html
nfafrontend/src/app/current-project/current-project.service.ts
nfafrontend/src/app/current-project/project-edit/project-edit.component.ts
nfafrontend/src/app/current-project/project-list/project-list.component.html
nfafrontend/src/app/current-project/project-list/project-list.component.ts
nfafrontend/src/app/newproject/newproject.component.ts
nfafrontend/src/app/shared/project.model.ts

Added archived Project View

---

.gitignore
nfabackend/pom.xml
nfabackend/src/main/java/com/msg/nfabackend/entities/Project.java
nfabackend/src/main/java/com/msg/nfabackend/entities/Type.java
nfabackend/src/main/java/com/msg/nfabackend/resources/TypeResource.java
nfabackend/src/main/java/com/msg/nfabackend/services/QueryService.java
nfabackend/src/main/resources-filtered/META-INF/persistence.xml
nfabackend/src/main/resources/ddl/NFADB.sql
nfafrontend/src/app/app-routing.module.ts
nfafrontend/src/app/current-project/current-project.component.html
nfafrontend/src/app/current-project/current-project.service.ts
nfafrontend/src/app/current-project/project-detail/project-detail.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.ts
nfafrontend/src/app/current-project/project-list/project-item/project-item.component.html
nfafrontend/src/app/current-project/project-list/project-list.component.html
nfafrontend/src/app/current-project/project-list/project-list.component.ts
nfafrontend/src/app/header/header.component.html
nfafrontend/src/app/newproject/newproject.component.ts
nfafrontend/src/app/shared/data-storage.service.ts
nfafrontend/src/app/shared/project.model.ts
nfafrontend/src/app/shared/type.model.ts
nfafrontend/src/assets/i18n/de.json
nfafrontend/src/assets/i18n/en.json
nfafrontend/src/index.html

- Inorder to check this pull request successfully, you have to run the sql script in your database.
- Sample test data insertions to tables are taken care by this script itself.
- Please find the SQL script in path - NFA-Tool\nfabackend\src\main\resources\ddl\NFADB.sql
Following changes are present in this part of code:
- Fused new project page and edit page.
- Changed Form Styles, Fonts.
- Used all the earlier implementations of team members and made little changes to them inorder to make the page appear good.
Hope you will like it. :-)

Cleanup in NFA-PROJECT page

---

nfafrontend/src/app/current-project/project-list/project-list.component.ts
nfafrontend/src/assets/i18n/de.json
nfafrontend/src/assets/i18n/en.json

change the default status in project list to be "on process" 
change the view current projects to view projects in home screen

small changes in home screen and project list

---

nfabackend/pom.xml
nfabackend/src/main/java/com/msg/nfabackend/entities/NfaCriteria.java
nfabackend/src/main/java/com/msg/nfabackend/entities/NfaFactor.java
nfabackend/src/main/java/com/msg/nfabackend/entities/Project.java
nfabackend/src/main/java/com/msg/nfabackend/entities/Stakeholder.java
nfabackend/src/main/java/com/msg/nfabackend/resources/StakeholderResource.java
nfabackend/src/main/java/com/msg/nfabackend/services/QueryService.java
nfabackend/src/main/resources-filtered/META-INF/persistence.xml
nfabackend/src/main/resources/ddl/NFADB.sql
nfafrontend/src/app/app-routing.module.ts
nfafrontend/src/app/app.module.ts
nfafrontend/src/app/current-project/current-project.service.ts
nfafrontend/src/app/current-project/project-edit/project-edit.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.ts
nfafrontend/src/app/current-project/stake-holder/stake-holder.component.html
nfafrontend/src/app/current-project/stake-holder/stake-holder.component.ts
nfafrontend/src/app/shared/data-storage.service.ts
nfafrontend/src/app/shared/project.model.ts
nfafrontend/src/app/shared/stakeholder.model.ts

Feature has the following : 
- Add multiple stakeholders and choose multiple factors under them. On clicking save data gets saved in database.
- Modified SQL file. Run SQL on your database before trying it.

Add stakeholder

---

nfabackend/src/main/java/com/msg/nfabackend/entities/Metric.java
nfabackend/src/main/java/com/msg/nfabackend/entities/NfaCriteria.java
nfabackend/src/main/java/com/msg/nfabackend/entities/NfaFactor.java
nfabackend/src/main/java/com/msg/nfabackend/entities/Project.java
nfabackend/src/main/resources-filtered/META-INF/persistence.xml
nfabackend/src/main/resources/ddl/NFADB.sql
nfafrontend/src/app/current-project/project-edit/project-edit.component.html
nfafrontend/src/assets/i18n/de.json
nfafrontend/src/assets/i18n/en.json

Added some Values to Branches. And cleaned a few things up.

msg-branches

---

nfabackend/src/main/java/com/msg/nfabackend/entities/Project.java
nfabackend/src/main/java/com/msg/nfabackend/services/QueryService.java
nfabackend/src/main/resources/ddl/NFADB.sql
nfafrontend/src/app/app-routing.module.ts
nfafrontend/src/app/app.module.ts
nfafrontend/src/app/current-project/assign-nfa/assign-nfa.component.html
nfafrontend/src/app/current-project/assign-nfa/assign-nfa.component.ts
nfafrontend/src/app/current-project/assign-nfa/choose-nfa/choose-nfa.component.html
nfafrontend/src/app/current-project/assign-nfa/choose-nfa/choose-nfa.component.ts
nfafrontend/src/app/current-project/assign-nfa/nfa-detail/nfa-detail.component.html
nfafrontend/src/app/current-project/assign-nfa/nfa-detail/nfa-detail.component.ts
nfafrontend/src/app/current-project/assign-nfa/nfa-list/nfa-item/nfa-item.component.html
nfafrontend/src/app/current-project/assign-nfa/nfa-list/nfa-item/nfa-item.component.ts
nfafrontend/src/app/current-project/assign-nfa/nfa-list/nfa-list.component.html
nfafrontend/src/app/current-project/assign-nfa/nfa-list/nfa-list.component.ts
nfafrontend/src/app/current-project/current-project.service.ts
nfafrontend/src/app/current-project/project-detail/project-detail.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.ts
nfafrontend/src/app/newnfa/newnfa.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-list.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-metric/nfacatalog-metric.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-metric/nfacatalog-metric.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-nfa/nfacatalog-nfa.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-list/nfacatalog-list.component.html
nfafrontend/src/app/shared/project.model.ts

Feature has following functions:
(Please run the NFADB.sql to update your DB with new tables)
- can go to choose-nfa page from project edit page.
- here you can see list of NFAs added to the project.
- Click assign-nfa button to choose nfa and assign it to project.
- Click + to add or X  to remove any particular NFA to/from project.
- Click project button to get back to project edit page.

Feature select

---

nfabackend/src/main/java/com/msg/nfabackend/services/QueryService.java
nfafrontend/src/app/current-project/assign-nfa/nfa-list/nfa-list.component.ts
nfafrontend/src/app/current-project/current-project.service.ts
nfafrontend/src/app/current-project/project-edit/project-edit.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.ts
nfafrontend/src/app/current-project/project-list/project-list.component.ts

Fixed assigning NFA to newly created project.

Choose nfa fix

---

nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-item/nfacatalog-criteria-item.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-item/nfacatalog-criteria-item.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-list.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-metric/nfacatalog-metric.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-metric/nfacatalog-metric.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-nfa/nfacatalog-nfa.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-nfa/nfacatalog-nfa.component.ts

displaying numbers of nfa, matric and criteria in nfa catalog

Sanjog catalog

---

nfabackend/pom.xml
nfabackend/src/test/java/entities/JPAHibernateTest.java
nfabackend/src/test/java/entities/MetricTest.java
nfabackend/src/test/resources/META-INF/persistence.xml
nfabackend/src/test/resources/create.sql

I added framework for testing ; started with metric but it isjust for testing:) and I will add more today night.
Steps to make it work !
Add database for testing with name nfatest
Change  properties with your credential in the testing persistence file

Testing framework

---

nfabackend/src/main/java/com/msg/nfabackend/services/QueryService.java
nfabackend/src/test/java/entities/ProjectTest.java

Added some tests to ProjectTest

testing-framework

---

nfafrontend/package.json
nfafrontend/src/app/app-routing.module.ts
nfafrontend/src/app/app.module.ts
nfafrontend/src/app/current-project/assign-nfa/nfa-detail/nfa-detail.component.ts
nfafrontend/src/app/current-project/current-project.service.ts
nfafrontend/src/app/current-project/project-detail/project-detail.component.ts
nfafrontend/src/app/current-project/project-edit/project-edit.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.ts
nfafrontend/src/app/current-project/project-list/project-list.component.ts
nfafrontend/src/app/header/header.component.html
nfafrontend/src/app/header/header.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-nfa/nfacatalog-nfa.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-nfa/nfacatalog-nfa.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog.component.html
nfafrontend/src/app/nfacatalog/nfacatalog.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog.service.ts

add the user selection in the local storage
it needs some changes in because the uncheck of the selection has not handled and some time the original NFA catalog page keeps cashed UI

navigate to the NFR  from the project page

---

nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-item/nfacatalog-criteria-item.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-list.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-list.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria.component.html

-Implementation of nav-tree in nfa-catalog.
-Allows us to navigate between factors.
-No changes done to NFADB.sql

Added nav tree to allow easy navigation between factors

---

nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-item/nfacatalog-criteria-item.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-item/nfacatalog-criteria-item.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-metric/nfacatalog-metric.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-metric/nfacatalog-metric.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-list/nfacatalog-item/nfacatalog-item.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-list/nfacatalog-item/nfacatalog-item.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-list/nfacatalog-list.component.ts

There is no change in backend and no added package to the front end :) 
the changes are in the nfacatalogitem - nfacriteriaitem and nfametric components and a very small change in html as well
I just highlight the displayed factor/criteria/metric if they have nfr belongs to the project.

highlight the (factors - criteria - metrics) according to the project's NFRs

---

nfafrontend/src/app/app-routing.module.ts
nfafrontend/src/app/app.component.html
nfafrontend/src/app/app.component.ts
nfafrontend/src/app/app.module.ts
nfafrontend/src/app/header/header.component.html
nfafrontend/src/app/header/header.component.ts
nfafrontend/src/app/login/login.component.html
nfafrontend/src/app/login/login.component.spec.ts
nfafrontend/src/app/login/login.component.ts
nfafrontend/src/app/shared/authentication.service.ts
nfafrontend/src/app/shared/guards/auth.guard.ts
nfafrontend/src/app/shared/handlers/backend.ts
nfafrontend/src/app/shared/handlers/jwt.interceptor.ts
nfafrontend/src/app/shared/user.service.ts
nfafrontend/src/app/shared/user.ts
nfafrontend/src/assets/i18n/de.json
nfafrontend/src/assets/i18n/en.json

-Added login page, which does not allow to move to the homepage, until login and password not added. 
TO DO: 
-Header on its place on purpose, planning to hide before login everything except button "Login" and logo.
-Connection with backend
-Something better, than writing TO DO in pull request :)

Front-end implementation of the login feature.

---

nfafrontend/src/app/app-routing.module.ts
nfafrontend/src/app/header/header.component.ts

pull dmitriis deactivated auth guards

login-decativated

---

nfafrontend/src/app/current-project/project-edit/project-edit.component.html
nfafrontend/src/app/current-project/project-edit/project-edit.component.ts

Changes done: 
- When agile selected make project phase disappear
- Display numbers beside factors while assigning it to stakeholder
- Restriction to add multiple project-typ.
- Removed unnecessary label and pre-scroll

Corrections in Create-Project page

---

nfafrontend/src/app/app.module.ts
nfafrontend/src/app/current-project/project-detail/project-detail.component.html
nfafrontend/src/app/current-project/project-list/project-list.component.html
nfafrontend/src/app/current-project/project-list/project-list.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-list.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-criteria/nfacatalog-criteria-list/nfacatalog-criteria-list.component.ts
nfafrontend/src/app/nfacatalog/nfacatalog-list/nfacatalog-list.component.html
nfafrontend/src/app/nfacatalog/nfacatalog-list/nfacatalog-list.component.ts
nfafrontend/src/app/ui/loading-spinner/loading-spinner.component.css
nfafrontend/src/app/ui/loading-spinner/loading-spinner.component.html
nfafrontend/src/app/ui/loading-spinner/loading-spinner.component.ts
nfafrontend/src/app/ui/wave-bar/wave-bar.component.css
nfafrontend/src/app/ui/wave-bar/wave-bar.component.html
nfafrontend/src/app/ui/wave-bar/wave-bar.component.ts

Has the following(For having better look while server takes time to send data): 
- loading wavebar in project page
- loading spinner in nfacatalog page
- loading wavebar in criteria page
- Aligned buttons and hrline

Loading spinner

---

nfabackend/src/main/resources/ddl/demo.sql

it includes fisrtly the database creation script then the first 5 factors with all metics, and nfas
secondly it includes project data for the demo

 demo script
